In [2]:
import pandas as pd
import numpy as np
import random

In [3]:
data_df = pd.read_csv("example-dataset.tsv", sep ="\t" )
data_df

,strain,region,date,sequence
0,NOKQPO,A,9.997260,ACGGAACCATCCGATTAATCCAGCAGGCCTACCAAACACTCCGGTG...
1,AOUZCQ,B,9.997260,ACGGAACCATCCGATTAATCCAGCACGCCTACTAAACACTCCGGTG...
2,SSYBIR,A,9.994520,ACGGAACCATCCGATTAATCCAGCACGCCTACTAAACACTCCGGTG...
3,AISSWJ,A,9.994520,ACGGAACCATCCGATTAATCCAGCAGGCCTACCAAACACTCCGGTG...
4,MQUFYN,B,9.994520,ACGGAACCATCCGATTAATCCAGCACGCCTACTAAACACTCCGGTG...
...,...,...,...,...
3984,OMEXHP,A,0.008219,ACGGAACCATCCGATGAATCCAGCACGCCTGCTAAACACTCCGGTG...
3985,LMCLJD,A,0.008219,ATGGAGCCATCCGACGAATCCAGCACACCTACTAAACACTCCGGTG...
3986,NFFOOT,A,0.008219,ATGGAACCATCCGACGAATCCAGCACACCTACTAAACACTCCGGTG...
3987,KEMEGI,B,0.005479,ATGGAGCCATCCGACGAATCCATCACACCTACTAAACACTCCGGTA...
3988,CSYXBT,A,0.005479,ATGGAGCCATCCGACGAATCCAGCACACCTACTAAACACTCCGGTG...

In [156]:
data_df["strain_name"] =data_df.strain.astype(str)+ "_" + data_df.region.astype(str) + "_" + data_df.date.astype(str)

In [149]:
data_df.region.value_counts()

A    2103
B    1886
Name: region, dtype: int64

In [151]:
unique_locations = data_df.region.unique().tolist(); unique_locations

['A', 'B']

In [196]:
def weighted_subsampling(weights_list):    
    temp_seqs = data_df.copy()
    temp_cases = pd.DataFrame()
    final_df = pd.DataFrame(columns = ["strain", "region", "date", "sequence"])
    sampled_locations = random.choices(population = unique_locations, weights = weights_list, k = 1000)
    #print(sampled_locations)
    for locations in sampled_locations:
        try:
            subset_seqs = pd.DataFrame()
            subset_seqs = temp_seqs[temp_seqs.region == locations].sample(1)
            temp_seqs.drop(subset_seqs.index, inplace = True)
            #print(subset_seqs)
            final_df = final_df.append(subset_seqs, ignore_index=True)
        except ValueError:
            continue 
    return final_df

In [201]:
weights_list = [0.5, 0.5]
equal_df = weighted_subsampling(weights_list)

/var/folders/h9/0347drb57tsgxzbddmvmlvf80000gp/T/ipykernel_95966/3382559098.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(subset_seqs, ignore_index=True)

In [202]:
equal_df.region.value_counts()

B    511
A    489
Name: region, dtype: int64

In [185]:
weights_list = [0.9, 0.1]
biased_df = weighted_subsampling(weights_list)

biased_df

/var/folders/h9/0347drb57tsgxzbddmvmlvf80000gp/T/ipykernel_95966/3382559098.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(subset_seqs, ignore_index=True)

,strain,region,date,sequence,strain_name
0,BYRKTM,A,0.369863,ATGGAACCATCCGACGAATCCAGCACACCTACTAAACACTCCGGTG...,BYRKTM_A_0.369863
1,IMPEND,A,9.087670,ACGGAACCATCCGATTAATCCAGCACGCCTACTAAACACTCCGGTG...,IMPEND_A_9.08767
2,YZHYHW,A,2.654790,ATGGAACCATCCGTCGAATCCAGCACACCTACTAAACACTCCGGTG...,YZHYHW_A_2.65479
3,PHHCJE,A,3.082190,ACGGAACCATCCGATGAATCCAGCACGCCTGCTAAACACTCCGGTG...,PHHCJE_A_3.08219
4,DVXKJD,A,3.717810,ACGGAACCATCCGATGAATCCAGCACGCCTGCTAAACACTCCGGTG...,DVXKJD_A_3.71781
...,...,...,...,...,...
995,JLHHFN,A,9.547950,ACGGAACCATCCGATTAATCCAGCACGCCTACTAAACACTCCGGTG...,JLHHFN_A_9.54795
996,XHPUJT,A,2.868490,ACGGAACCATCCGATGAATCCAGCACGCCTACTAAACACTCCGGTG...,XHPUJT_A_2.86849
997,TCVDBE,A,7.002740,ACGGAACCATCCGATGAATCCAGCACGCCTACTAAACACTCCGGTG...,TCVDBE_A_7.00274
998,NBDBDX,A,9.843840,ACGGAACCATCCGATTAATCCAGCACGCCTACTAAACACTCCGGTG...,NBDBDX_A_9.84384
999,FHCZZC,A,5.901370,ACGGAACCATCCGATGAATCCTGCACGCCTACTAAACACTCCGGTG...,FHCZZC_A_5.90137

In [186]:
weights_list = [0.9, 0.1]
biased_df = biased_df(weights_list)

biased_df

/var/folders/h9/0347drb57tsgxzbddmvmlvf80000gp/T/ipykernel_95966/3382559098.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = final_df.append(subset_seqs, ignore_index=True)

,strain,region,date,sequence,strain_name
0,AVUPKZ,B,0.027397,ATGGAGCCATCCGACGAATCCAGCACACCTACTAAACACTCCGGTG...,AVUPKZ_B_0.0273973
1,UAOUMN,B,3.435620,ATGGAACCATCCGACGAATCCAGCACACCTACTAAACACTCCGGTG...,UAOUMN_B_3.43562
2,KKEZRL,B,3.013700,ATGGAACCATCCGACGAATCCAGCACACCTACTAAACACTCCGGTG...,KKEZRL_B_3.0137
3,QFOINA,B,4.975340,ATGGAACCATCCGATGAATCCAGCACACCTACTAAACACTCCGGTG...,QFOINA_B_4.97534
4,EZKAPS,B,3.501370,ATGGAACCATCCGTCGAATCCAGCACACCTACTAAACACTCCGGTG...,EZKAPS_B_3.50137
...,...,...,...,...,...
995,GHRQIN,B,4.238360,ATGGAACCATCCGATGAATCCAGCACACCTACTAAACACTCCGGTG...,GHRQIN_B_4.23836
996,LRYWRJ,B,5.605480,ATGGAACCATCCGATGAATCCAGCACGCCTACTAAACACTCCGGTG...,LRYWRJ_B_5.60548
997,VAPTXY,B,8.139730,ACGGAACCATCCGATTAATCCAGCACGCCTACTAAACACTCCGGTG...,VAPTXY_B_8.13973
998,PDMEMJ,B,3.161640,ATGGAACCATCCGATGAATCCAGCACACCTACTAAACACTCCGGTG...,PDMEMJ_B_3.16164
999,TGDQLF,B,6.295890,ACGGAACCATCCGATTAATCCAGCACGCCTACTAAACACTCCGGTG...,TGDQLF_B_6.29589

In [187]:
biased_df.region.value_counts()

A    909
B     91
Name: region, dtype: int64

In [188]:
biased_df = biased_df[["strain_name", "sequence"]]
equal_df = equal_df[["strain_name", "sequence"]]

In [189]:
biased_df.to_csv("biased_samples.txt", sep = "\t", index = False, header = False)
equal_df.to_csv("equal_samples.txt", sep = "\t", index = False, header = False)